services:

####################################################################################################
# app
####################################################################################################
  app-extremadura:
    build:
      args:
        user: developer
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: app-extremadura
    container_name: app-extremadura
    restart: unless-stopped
    links:
      - mysql-extremadura
    environment:
      VIRTUAL_HOST: extremadura.cultureplex.co
    working_dir: /var/www/
    volumes:
      - app-extremadura:/var/www
      - ~/.ssh:/root/.ssh
    depends_on:
      - mysql-extremadura
      - redis-extremadura
    networks:
      - laravel

####################################################################################################
# DATABASE (MySQL)
####################################################################################################
  mysql-extremadura:
    image: mysql:8.0
    container_name: mysql-extremadura
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_HOST: '%' # Allow connections from any host
      MYSQL_ROOT_HOST: '%' # Allow connections from any host
    volumes:
      - mysql-extremadura/var/lib/mysql:/var/lib/mysql
      - mysql-extremadura/var/log/mysql:/var/log/mysql
    networks:
      - laravel

####################################################################################################
# Nginx
####################################################################################################
  nginx-extremadura:
    image: nginx:alpine
    container_name: nginx-extremadura
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - app-extremadura:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
      - ./docker-compose/nginx/ssl:/etc/nginx/conf.d/ssl
      - ./docker-compose/nginx/phpMyAdmin.conf:/etc/nginx/conf.d/phpMyAdmin.conf
    networks:
      - laravel

####################################################################################################
# phpMyAdmin
####################################################################################################
  phpmyadmin-extremadura:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-extremadura
    ports:
        - 8080:80
    links:
        - mysql-extremadura
    restart: unless-stopped
    environment:
        PMA_HOST: mysql-extremadura
        #PMA_USER: ${DB_USERNAME}
        #PMA_PASSWORD: ${DB_PASSWORD}
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
    networks:
        - laravel

 ####################################################################################################
# Redis
####################################################################################################
  redis-extremadura:
    image: "redis:alpine"
    container_name: redis-extremadura
    restart: unless-stopped
    volumes:
        - ./docker-compose/redis/data:/data
    ports:
      - "6379:6379"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mysql-extremadura:
  redis-extremadura:
  app-extremadura:
